language: objective-c
osx_image: xcode7.1
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
    - cd Project
script: xctool -project JSONAPI.xcodeproj -scheme JSONAPI -sdk iphonesimulator test
