language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
script: xctool -project Project/JSONAPI.xcodeproj -scheme JSONAPI -sdk iphonesimulator test
